name: Go
on: [push, pull_request]
jobs:

  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: false
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build -v .

    - name: Checkout test XSD
      uses: actions/checkout@v4
      with:
        repository: xuri/xsd
        path: data

    - name: Test
      run: go test -v -timeout 60m -coverprofile='coverage.txt' -covermode=atomic ./

    - name: Check that generated files are up to date
      run: |
        cd cmd/xgen && \
        go install && \
        cd ../.. &&
        xgen -i ./test/xsd/base64.xsd -o ./test/c/base64.xsd.h -l C && \
        xgen -i ./test/xsd/base64.xsd -o ./test/go/base64.xsd.go -l Go && \
        xgen -i ./test/xsd/base64.xsd -o ./test/java/base64.xsd.java -l Java && \
        xgen -i ./test/xsd/base64.xsd -o ./test/rs/base64.xsd.rs -l Rust && \
        xgen -i ./test/xsd/base64.xsd -o ./test/ts/base64.xsd.ts -l TypeScript && \
        git diff --exit-code

    - name: Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage.txt
        flags: unittests
        name: codecov-umbrella